apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8080 # Port externe pour accéder au service
    targetPort: 8080 # Port interne de l'application Node.js
  type: LoadBalancer
